/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.altimetrik.chatBot.controllerInf;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.altimetrik.chatBot.entities.Menu;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-11-27T09:47:09.303Z")

@Api(value = "menus", description = "the menus API")
public interface MenusApi {

    @ApiOperation(value = "get all menue", nickname = "getMenu", notes = "get all the relevent menue", response = Menu.class, responseContainer = "List", tags={ "chatbotMenu", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "generate successfuly bill", response = Menu.class, responseContainer = "List"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/menus",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.GET)
    ResponseEntity<List<Menu>> getMenu(@ApiParam(value = "menu object"  )  @Valid @RequestBody Menu body);

}
